version: '2'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    build:
      context: handler/.
      dockerfile: Dockerfile
    ports:
      - "8889:8889"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

